layout_spectrum: 0.8282527711708099
typography_spectrum: 0.46378357405774295
color:
  brandStrength: 0.10256241983734071
  lightness: 0.18201384553685784
  saturation: 0.6114678864832968
  rhythmicContrast: 0.7722081686370075
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
author:
  url: www.marijuanamastery.com
name: Marijuanamastery.com
navigation:
  - name: Buy your copy of 7 Steps To Marijuana Mastery
    url: >-
      https://www.amazon.com/7-Steps-Marijuana-Mastery-Gold-ebook/dp/B01GXEOMTQ/ref=sr_1_1?s=books&ie=UTF8&qid=1470283859&sr=1-1&keywords=7+steps+to+marijuana+mastery#nav-subnav
    type: external
  - name: Read more about 7 Steps To Marijuana Mastery
    id: e9b8e7d3-cd60-46e9-b5f7-92676aadabd7
    type: content
