typography_spectrum: 0.7150662934873253
color:
  brandStrength: 0.6121460851281881
  lightness: 0.023963049985468388
  saturation: 0.10047986381687224
  rhythmicContrast: 0.645246725063771
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
layout_spectrum: 0.46420718962326646
author:
  url: www.marijuanamastery.com
name: Marijuanamastery.com
navigation:
  - name: Buy your copy of 7 Steps To Marijuana Mastery
    url: >-
      https://www.amazon.com/7-Steps-Marijuana-Mastery-Gold-ebook/dp/B01GXEOMTQ/ref=sr_1_1?s=books&ie=UTF8&qid=1470283859&sr=1-1&keywords=7+steps+to+marijuana+mastery#nav-subnav
    type: external
